apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-167782365
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-167782365
    app.kubernetes.io/part-of: test-app-167782365
  name: java-quarkus-167782365
  namespace: skhileri-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-167782365
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-167782365
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:75ba7aa5b42f66771d17eef33bcbb7487283eaac0df73dcb8236cf853d70ab58
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
