apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-167782365
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-167782365
    app.kubernetes.io/part-of: test-app-167782365
  name: java-quarkus-167782365
  namespace: skhileri-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: java-quarkus-167782365
status:
  loadBalancer: {}
